type SurrealTypes* = enum
    ## Supported Surreal types

    SurrealInteger,
    SurrealBytes,
    SurrealString,
    SurrealArray,
    SurrealObject,

    # SurrealNone,
    # SurrealNull,

    # SurrealArray,
    # SurrealBool,
    # SurrealBytes,
    # SurrealDatetime,
    # SurrealDecimal,
    # SurrealDuration,
    # SurrealFloat,
    # SurrealGeometry,
    # SurrealInt,
    # SurrealNumber,
    # SurrealObject,
    # SurrealLiteral,
    # SurrealOption,
    # SurrealRange,
    # SurrealRecord,
    # SurrealSet,
    # SurrealString,
    # SurrealUuid,